export const permissionSeed = [
  { key: "tenants.read", name: "Read tenants" },
  { key: "tenants.write", name: "Write tenants" },
  { key: "brands.read", name: "Read brands" },
  { key: "brands.write", name: "Write brands" },
  { key: "stores.read", name: "Read stores" },
  { key: "stores.write", name: "Write stores" },
  { key: "users.read", name: "Read users" },
  { key: "users.write", name: "Write users" },
  { key: "roles.read", name: "Read roles" },
  { key: "roles.write", name: "Write roles" },
  { key: "devices.read", name: "Read devices" },
  { key: "devices.write", name: "Write devices" },
  { key: "audit.read", name: "Read audit log" },
  { key: "settings.read", name: "Read settings" },
  { key: "settings.write", name: "Write settings" },
  { key: "feature_flags.read", name: "Read feature flags" },
  { key: "feature_flags.write", name: "Write feature flags" },
  { key: "categories.read", name: "Read categories" },
  { key: "categories.write", name: "Write categories" },
  { key: "products.read", name: "Read products" },
  { key: "products.write", name: "Write products" },
  { key: "modifiers.read", name: "Read modifiers" },
  { key: "modifiers.write", name: "Write modifiers" },
  { key: "pricing.read", name: "Read pricing" },
  { key: "pricing.write", name: "Write pricing" }
] as const;
