export const permissionSeed = [
  { key: "tenants.read", name: "Read tenants" },
  { key: "tenants.write", name: "Write tenants" },
  { key: "brands.read", name: "Read brands" },
  { key: "brands.write", name: "Write brands" },
  { key: "stores.read", name: "Read stores" },
  { key: "stores.write", name: "Write stores" },
  { key: "users.read", name: "Read users" },
  { key: "users.write", name: "Write users" },
  { key: "roles.read", name: "Read roles" },
  { key: "roles.write", name: "Write roles" },
  { key: "devices.read", name: "Read devices" },
  { key: "devices.write", name: "Write devices" },
  { key: "audit.read", name: "Read audit log" },
  { key: "settings.read", name: "Read settings" },
  { key: "settings.write", name: "Write settings" },
  { key: "feature_flags.read", name: "Read feature flags" },
  { key: "feature_flags.write", name: "Write feature flags" },
  { key: "customization.read", name: "Read customization layer" },
  { key: "customization.write", name: "Write customization layer" },
  { key: "categories.read", name: "Read categories" },
  { key: "categories.write", name: "Write categories" },
  { key: "products.read", name: "Read products" },
  { key: "products.write", name: "Write products" },
  { key: "modifiers.read", name: "Read modifiers" },
  { key: "modifiers.write", name: "Write modifiers" },
  { key: "pricing.read", name: "Read pricing" },
  { key: "pricing.write", name: "Write pricing" },
  { key: "carts.read", name: "Read carts" },
  { key: "carts.write", name: "Write carts" },
  { key: "orders.read", name: "Read orders" },
  { key: "orders.write", name: "Write orders" },
  { key: "order_events.read", name: "Read order events" },
  { key: "pos.read", name: "Read POS runtime" },
  { key: "pos.write", name: "Write POS runtime" },
  { key: "kitchen.read", name: "Read kitchen runtime" },
  { key: "kitchen.write", name: "Write kitchen runtime" },
  { key: "board.read", name: "Read order board" },
  { key: "kiosk.read", name: "Read kiosk runtime" },
  { key: "payments.read", name: "Read payments runtime" },
  { key: "payments.write", name: "Write payments runtime" },
  { key: "payment_configs.read", name: "Read payment provider configs" },
  { key: "payment_configs.write", name: "Write payment provider configs" },
  { key: "analytics.read", name: "Read analytics and owner cabinet" },
  { key: "analytics.write", name: "Write analytics snapshots" },
  { key: "customers.read", name: "Read customer profiles and promotions" },
  { key: "customers.write", name: "Write customer profiles, loyalty, and promotions" }
] as const;
