import type { AdminNavItem } from "@exetron/contracts";

export const adminNavigation: AdminNavItem[] = [
  { href: "/dashboard", label: "Overview" },
  { href: "/tenants", label: "Tenants" },
  { href: "/brands", label: "Brands" },
  { href: "/categories", label: "Categories" },
  { href: "/products", label: "Products" },
  { href: "/product-variants", label: "Variants" },
  { href: "/modifiers", label: "Modifier Groups" },
  { href: "/modifier-options", label: "Modifier Options" },
  { href: "/price-lists", label: "Price Lists" },
  { href: "/catalog-overrides", label: "Catalog Overrides" },
  { href: "/stores", label: "Stores" },
  { href: "/users", label: "Users" },
  { href: "/roles", label: "Roles & Permissions" },
  { href: "/devices", label: "Devices" },
  { href: "/owner-cabinet", label: "Owner Cabinet" },
  { href: "/customers", label: "Customers & Loyalty" },
  { href: "/payment-provider-configs", label: "Payment Configs" },
  { href: "/payments", label: "Payments" },
  { href: "/payment-reconciliation", label: "Reconciliation" },
  { href: "/kitchen", label: "Kitchen" },
  { href: "/order-board", label: "Order Board" },
  { href: "/fulfillment", label: "Fulfillment" },
  { href: "/settings", label: "Settings" },
  { href: "/localization", label: "Localization" },
  { href: "/feature-flags", label: "Feature Flags" },
  { href: "/customization", label: "Customization" },
  { href: "/audit", label: "Audit Trail" }
];
